version: '3'
services:
  web:
    build: .
    image: clagomess/docker-php-5.2
    network_mode: "bridge"
    ports:
      - "8000:80"
    volumes:
      - .:/usr/local/apache2/htdocs
    command: "/usr/local/apache2/bin/apachectl -D FOREGROUND"
